import { readdir, readFile } from "node:fs/promises";
import * as path from "node:path";

export const normalizeBundleOutput = (bundle: string) =>
    bundle
        .replace(
            /^-- Generated by @cc-ts\/builder@.+$/m,
            "-- Generated by @cc-ts/builder@<version>"
        )
        .replace(/^-- Hash: .+$/m, "-- Hash: <hash>")
        .replace(/^-- BuildTime: .+$/m, "-- BuildTime: <build-time>");

async function collectFiles(rootDir: string, currentDir = rootDir) {
    const entries = await readdir(currentDir, { withFileTypes: true });
    const files: string[] = [];

    for (const entry of entries) {
        const entryPath = path.join(currentDir, entry.name);
        if (entry.isDirectory()) {
            files.push(...(await collectFiles(rootDir, entryPath)));
            continue;
        }

        files.push(path.relative(rootDir, entryPath));
    }

    return files.sort();
}

const normalizeArtifact = (relativePath: string, content: string) => {
    if (relativePath.endsWith(".lua")) {
        return normalizeBundleOutput(content);
    }

    if (relativePath.endsWith(".map")) {
        return JSON.parse(content) as Record<string, unknown>;
    }

    return content;
};

export async function readNormalizedDistArtifacts(
    projectDir: string,
    { includeSourceMaps = false }: { includeSourceMaps?: boolean } = {}
) {
    const distDir = path.join(projectDir, "dist");
    const files = await collectFiles(distDir);
    const artifacts: Record<string, unknown> = {};

    for (const relativePath of files) {
        if (!includeSourceMaps && relativePath.endsWith(".map")) {
            continue;
        }

        const content = await readFile(path.join(distDir, relativePath), "utf8");
        artifacts[relativePath.replaceAll(path.sep, "/")] = normalizeArtifact(
            relativePath,
            content
        );
    }

    return artifacts;
}
